<h3>Login</h3>
<br>

<?php if ($this->error) : ?>
    <p>Usuário ou senha inválidos</p>
<?php endif; ?>

<?php

$form = $this->form;

$form->setAttribute('action', $this->url('user-auth'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <label class="col-xs-2 control-label">E-mail: </label>

    <div class="col-xs-10">
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
</div>


<div class="form-group">
    <label class="col-xs-2 control-label">Senha: </label>

    <div class="col-xs-10">
        <?php echo $this->formRow($form->get('password')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-10 col-xs-offset-2">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>
