<h3>Novo Usuário</h3>

<?php if ($this->messages): ?>
    <p><?php var_dump($this->messages); ?></p>
<?php endif; ?>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user-admin/default', array('controller' => 'users', 'action' => 'new')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="row">
    <div class="col-xs-6">
        <div class="form-group">
            <label class="col-xs-2 control-label">Nome: </label>

            <div class="col-xs-10">
                <?php echo $this->formRow($form->get('nome')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">
            <label class="col-xs-2 control-label">E-mail: </label>

            <div class="col-xs-10">
                <?php echo $this->formRow($form->get('email')); ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-6">
        <div class="form-group">
            <label class="col-xs-2 control-label">Senha: </label>

            <div class="col-xs-10">
                <?php echo $this->formRow($form->get('password')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">
            <label class="col-xs-2 control-label">Redigite: </label>

            <div class="col-xs-10">
                <?php echo $this->formRow($form->get('confirmation')); ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-6">
        <div class="form-group">
            <div class="col-xs-10 col-xs-offset-2">
                <?php echo $this->formRow($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>


<?php
echo $this->formHidden($form->get('security'));
echo $this->form()->closeTag();
?>