<h3>Editando Resource</h3>

<br>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('acl-admin/default', array('controller' => 'resources', 'action' => 'edit')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
#echo $this->formCollection($form);
?>

<div class="form-group">
    <label class="col-xs-2 control-label">Nome:</label>
    <div class="col-xs-10">
        <?php echo $this->formRow($form->get('nome')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-10 col-xs-offset-2">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>